require'nvim-treesitter.configs'.setup {
  ensure_installed = {
    "bash",
    "c",
    "comment",
    "css",
    "dockerfile",
    "go",
    "gomod",
    "gowork",
    "help",
    "html",
    "http",
    "javascript",
    "json",
    "make",
    "proto",
    "regex",
    "ruby",
    "toml",
    "vim",
    "yaml",
  },
  highlight = {
    enable = true,
    additional_vim_regex_highlighting = false,
  },
}
